import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';
import Session from "@/components/session";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import BottomHeader from "@/components/Navbar/BottomHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Glowing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
      <Theme appearance='light' accentColor='brown'>
      <Session>
      <Navbar/>
      <BottomHeader/>
        {children}
        <Footer/>
      </Session>
      </Theme>
  
      </body>
    </html>
  );
}